### PR TITLE
Add pool-aware interface and trait

### PR DESCRIPTION
**Pull request by garex**
Ok let's try here.

### CODE REVIEW

**Comment by michaelcullum** [comment]
@Crell Merge if you wish

**Review by michaelcullum — APPROVED** [review]

**Comment by Crell** [comment]
I'm skeptical here.  Certainly it can be done, but is it wise?  How often will you be side-injecting a cache pool?  It's not like the logger where it's more common to have a blanket "if it's loggable give it a logger" routine in your DI Container.

**Comment by garex** [comment]
@Crell how do you inject cache pool usually? As a constructor param?

I think cache is an often used feature, which can have it's own trait same as logger. Because it's a infrastructure layer.

**Comment by Crell** [comment]
Yes, constructor injection is preferred in virtually all cases.  Setter injection is really only useful for cases like the logger, or maybe ContainerAware (which is usually a code smell), where an _optional_ dependency can be passed in by a DI Container or factory selectively, based on the presence of an interface.  The use cases for that pattern are, IMO, very slim, and I don't think cache is one of them.  I'm actually hard pressed to think of any other than than ContainerAware or LoggerAware, now that I think of it...

**Comment by garex** [comment]
@Crell cache could be optional. That's why we have null-objects adapters both in stash and in symfony/cache.

**Pull request closed without merging**
