### PR TITLE
Update to latest PHPUnit in the 1.x branch

### PR DESCRIPTION
**Pull request by jbboehr**
This will allow the tests for 1.x to pass on PHP 8.0.

### CODE REVIEW

**Comment by jbboehr** [comment]
Oof. Didn't realize you were still testing against PHP 5.x.

**Comment by jbboehr** [comment]
AFAICT cache-util 1.x works fine on PHP 8.0, but not sure if there's a way to test against both PHP 5 and PHP 8 at the same time without some shenanigans.

**Comment by jbboehr** [comment]
In case you are wondering why I care, I test [my extension](https://github.com/jbboehr/php-psr) by running the test suite for various libraries with my extension loaded to make sure I'm implementing the interfaces correctly, and well I can't run your unit tests under php8 without patching your composer.json. Not a big deal but would be nice.

**Comment by jbboehr** [comment]
Looks like they're running fine with latest phpunit and PHP 8: https://github.com/jbboehr/cache-util/actions/runs/737669091

**Comment by Crell** [comment]
I would expect anyone using PHP 8 would be using the 2.x code anyway, not 1.x.  If not, they should be. :smile:  So I don't think it's worth investing any shenanigans in the 1.x branch's testing infrastructure.

If the 2.x code doesn't test well on 8.0, that's a problem, though.  Pretty sure it's fine.

**Pull request closed without merging**
