### PR TITLE
adds boilerplate exceptions and tests

### PR DESCRIPTION
**Pull request by bshaffer**
addresses #4

### CODE REVIEW

**Comment by dragoonis** [comment]
Looks good to me 👍

**Comment by michaelcullum** [comment]
@php-fig/psr-6. No objections from me as this is a util repo.

**Comment by Crell** [comment]
Thanks!  The test class seems rather pointless, though.  Let's just drop that file and commit the rest.

**Comment by bshaffer** [comment]
The test ensures the exceptions implement the interface correctly. So, the
proper methods are implemented, there isn't a typo in the interface name,
and there are no syntax errors. I feel like this is a good test to have!
But I can remove it if you'd like :)

**Comment by Crell** [comment]
Erf. I just merged #2, which included one of these exceptions. Sorry. :-(  It will need to get rerolled for just the one remaining exception.

And yeah, let's not bother with the test. It's not worth duplicating the type checking.

**Comment by bshaffer** [comment]
@Crell PTAL

**Comment by michaelcullum** [comment]
Looks fine to me now. @Crell Please review and adjust labels to say awaiting sec action.

**Pull request merged**
